default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_analytics_app_development
  username: postgres
  password: <%= ENV["SEARCH_ANALYTICS_APP_DATABASE_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: search_analytics_app_test
  username: postgres
  password: <%= ENV["SEARCH_ANALYTICS_APP_DATABASE_PASSWORD"] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
